### ISSUE TITLE
petermcottle.com fails to load over https in chrome since it tries to load jquery with http

### ISSUE THREAD

**Issue by auctome** [pcottle/PeterMCottle.com#3]
attempting to load PeterMCottle.com/ in chrome redirects to https://pcottle.github.io/PeterMCottle.com/ 
error in console
`Mixed Content: The page at 'https://pcottle.github.io/PeterMCottle.com/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.`

**Comment by pcottle** [comment]
Oh good catch! I think I just need to serve the jQuery file over https as well...

**Comment by pcottle** [comment]
Lets see if this works:
https://github.com/pcottle/PeterMCottle.com/commit/72f52714f7e53ab10c0bc8acbc83fc90d89436e8

**Comment by pcottle** [comment]
Think it works now after a hard-refresh:
https://pcottle.github.io/PeterMCottle.com/
